### ISSUE TITLE
[BUG] error: [BLOCKCHAIN] First block is not the Genesis block

### ISSUE THREAD

**Issue by minsulee2** [ainblockchain/ain-blockchain#182] opened 2021-01-20 02:00 UTC
**Describe the bug**
When the first node is started and nobody comes, after that, terminates the first node and restart! then it faces error :(

**To Reproduce**
1. [Tracker] node tracker-server/index.js
2. [Node1] NUM_VALIDATORS=2 ACCOUNT_INDEX=0 HOSTING_ENV=local node client/index.js
3. [Node2] DO NOTHING
4. [Node1] ctrl + c (terminate the node)
5. [Node1] NUM_VALIDATORS=2 ACCOUNT_INDEX=0 HOSTING_ENV=local node client/index.js again

**Expected behavior**
The [Node1] should be wait for other nodes in a peaceful manner.

**Comment by platfowner** [comment] 2021-01-26 02:40
Caused by created_at field newly introduced recently to Transaction class.

**Comment by liayoo** [comment] 2021-01-26 03:38
Fixed by #189

**Closed by liayoo** 2021-01-26 03:38 UTC
Labels: bug
